kind: pipeline
type: docker
name: greeting

steps:
  - name: en
    image: alpine
    commands:
      - echo hello world

  - name: fr
    image: alpine
    commands:
      - echo bonjour monde

  - name: ab
      image: alpine
      commands:
        - echo bonjour monde